Description of gauss_rnd
Home > src > gauss_rnd.m
gauss_rnd
PURPOSE
GAUSS_RND Multivariate Gaussian random variables
SYNOPSIS
function X = gauss_rnd(M,S,N)
DESCRIPTION
GAUSS_RND  Multivariate Gaussian random variables
 Syntax:
   P = GAUSS_RND(M,S,N)
 In:
   M - Dx1 mean of distibution or K values as DxK matrix.
   S - DxD covariance matrix
   N - Number of samples (optional, default 1)
 Out:
   X - Dx(K*N) matrix of samples.
 Description:
   Draw N samples from multivariate Gaussian distribution
     X ~ N(M,S)
 See also:
   GAUSS_PDF
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ekf_sine_demo Demonstration for EKF using a random sine signal model.
kf_cwpa_demo A very simple demo for the classical Kalman filter and smoother
ungm_demo Demonstration of univariate nonstationary growth model (UNGM) using EKF and UKF.
ungm_demo Demonstration of univariate nonstationary growth model (UNGM) using
SOURCE CODE
%GAUSS_RND  Multivariate Gaussian random variables
%
% Syntax:
%   P = GAUSS_RND(M,S,N)
%
% In:
%   M - Dx1 mean of distibution or K values as DxK matrix.
%   S - DxD covariance matrix
%   N - Number of samples (optional, default 1)
%
% Out:
%   X - Dx(K*N) matrix of samples.
%
% Description:
%   Draw N samples from multivariate Gaussian distribution
%
%     X ~ N(M,S)
%
% See also:
%   GAUSS_PDF
% Copyright (C) 2002-2006 Simo Särkkä
%
% $Id: gauss_rnd.m,v 1.2 2006/10/29 21:18:42 ssarkka Exp $
%
% This software is distributed under the GNU General Public
% Licence (version 2 or later); please refer to the file
% Licence.txt, included with the software, for details.
function X = gauss_rnd(M,S,N)
  if nargin < 3
    N = 1;
  end
  L = chol(S)';
  X = repmat(M,1,N) + L*randn(size(M,1),size(M,2)*N);