Description of kf_predict
Home > src > kf_predict.m
kf_predict
PURPOSE
KF_PREDICT Perform Kalman Filter prediction step
SYNOPSIS
function [x,P] = kf_predict(x,P,A,Q,B,u)
DESCRIPTION
KF_PREDICT  Perform Kalman Filter prediction step
 Syntax:
   [X,P] = KF_PREDICT(X,P,A,Q,B,U)
 Author:
   Simo Särkkä <simo.sarkka@hut.fi>, 2002
   Jouni Hartikainen <jmjharti@cc.hut.fi>, 2007
 In:
   X - Nx1 mean state estimate of previous step
   P - NxN state covariance of previous step
   A - Transition matrix of discrete model (optional, default identity)
   Q - Process noise of discrete model     (optional, default zero)
   B - Input effect matrix                 (optional, default identity)
   U - Constant input                      (optional, default empty)
 Out:
   X - Predicted state mean
   P - Predicted state covariance
 Description:
   Perform Kalman Filter prediction step. The model is
     x[k] = A*x[k-1] + B*u[k-1] + q,  q ~ N(0,Q).
   The predicted state is distributed as follows:
     p(x[k] | x[k-1]) = N(x[k] | A*x[k-1] + B*u[k-1], Q[k-1])
   The predicted mean x-[k] and covariance P-[k] are calculated
   with the following equations:
     m-[k] = A*x[k-1] + B*u[k-1]
     P-[k] = A*P[k-1]*A' + Q.
   If there is no input u present then the first equation reduces to
     m-[k] = A*x[k-1]
 History:
   26.2.2007 JH Added the distribution model for the predicted state
                and equations for calculating the predicted state mean and
                covariance to the description section.
 See also:
   KF_UPDATE, LTI_DISC, EKF_PREDICT, EKF_UPDATE
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
kf_cwpa_demo A very simple demo for the classical Kalman filter and smoother
kf_sine_demo Kalman Filter demonstration with sine signal.
fbf_smooth FBF_SMOOTH Forward-Backward Filtering Based Smoother
kf_loop KF_LOOP Performs the prediction and update steps of the Kalman filter
SOURCE CODE
%KF_PREDICT  Perform Kalman Filter prediction step
%
% Syntax:
%   [X,P] = KF_PREDICT(X,P,A,Q,B,U)
%
% Author:
%   Simo Särkkä <simo.sarkka@hut.fi>, 2002
%   Jouni Hartikainen <jmjharti@cc.hut.fi>, 2007
%
% In:
%   X - Nx1 mean state estimate of previous step
%   P - NxN state covariance of previous step
%   A - Transition matrix of discrete model (optional, default identity)
%   Q - Process noise of discrete model     (optional, default zero)
%   B - Input effect matrix                 (optional, default identity)
%   U - Constant input                      (optional, default empty)
%
% Out:
%   X - Predicted state mean
%   P - Predicted state covariance
%
% Description:
%   Perform Kalman Filter prediction step. The model is
%
%     x[k] = A*x[k-1] + B*u[k-1] + q,  q ~ N(0,Q).
%
%   The predicted state is distributed as follows:
%
%     p(x[k] | x[k-1]) = N(x[k] | A*x[k-1] + B*u[k-1], Q[k-1])
%
%   The predicted mean x-[k] and covariance P-[k] are calculated
%   with the following equations:
%
%     m-[k] = A*x[k-1] + B*u[k-1]
%     P-[k] = A*P[k-1]*A' + Q.
%
%   If there is no input u present then the first equation reduces to
%     m-[k] = A*x[k-1]
%
% History:
%
%   26.2.2007 JH Added the distribution model for the predicted state
%                and equations for calculating the predicted state mean and
%                covariance to the description section.
%
% See also:
%   KF_UPDATE, LTI_DISC, EKF_PREDICT, EKF_UPDATE
% Copyright (C) 2002-2006 Simo Särkkä
%
% $Id: kf_predict.m,v 1.2 2006/10/04 18:26:19 ssarkka Exp $
%
% This software is distributed under the GNU General Public
% Licence (version 2 or later); please refer to the file
% Licence.txt, included with the software, for details.
function [x,P] = kf_predict(x,P,A,Q,B,u)
  %
  % Check arguments
  %
  if nargin < 3
    A = [];
  end
  if nargin < 4
    Q = [];
  end
  if nargin < 5
    B = [];
  end
  if nargin < 6
    u = [];
  end
  %
  % Apply defaults
  %
  if isempty(A)
    A = eye(size(x,1));
  end
  if isempty(Q)
    Q = zeros(size(x,1));
  end
  if isempty(B) & ~isempty(u)
    B = eye(size(x,1),size(u,1));
  end
  %
  % Perform prediction
  %
  if isempty(u)
    x = A * x;
    P = A * P * A' + Q;
  else
    x = A * x + B * u;
    P = A * P * A' + Q;
  end