Description of lti_disc
Home > src > lti_disc.m
lti_disc
PURPOSE
LTI_DISC Discretize LTI ODE with Gaussian Noise
SYNOPSIS
function [A,Q] = lti_disc(F,L,Q,dt)
DESCRIPTION
LTI_DISC  Discretize LTI ODE with Gaussian Noise
 Syntax:
   [A,Q] = lti_disc(F,L,Qc,dt)
 Author:
   Simo Särkkä, 2002, 2003
 In:
   F  - NxN Feedback matrix
   L  - NxL Noise effect matrix        (optional, default identity)
   Qc - LxL Diagonal Spectral Density  (optional, default zeros)
   dt - Time Step                      (optional, default 1)
 Out:
   A - Transition matrix
   Q - Discrete Process Covariance
 Description:
   Discretize LTI ODE with Gaussian Noise. The original
   ODE model is in form
     dx/dt = F x + L w,  w ~ N(0,Qc)
   Result of discretization is the model
     x[k] = A x[k-1] + q, q ~ N(0,Q)
   Which can be used for integrating the model
   exactly over time steps, which are multiples
   of dt.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bot_demo_all Bearings Only Tracking (BOT demonstration with EKF1,EKF2 and UKF
ekfs_bot_demo %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ukfs_bot_demo Bearings Only Tracking (BOT) demonstration with UKF.
ekf_sine_demo Demonstration for EKF using a random sine signal model.
kf_cwpa_demo A very simple demo for the classical Kalman filter and smoother
kf_sine_demo Kalman Filter demonstration with sine signal.
SOURCE CODE
%LTI_DISC  Discretize LTI ODE with Gaussian Noise
%
% Syntax:
%   [A,Q] = lti_disc(F,L,Qc,dt)
%
% Author:
%   Simo Särkkä, 2002, 2003
%
% In:
%   F  - NxN Feedback matrix
%   L  - NxL Noise effect matrix        (optional, default identity)
%   Qc - LxL Diagonal Spectral Density  (optional, default zeros)
%   dt - Time Step                      (optional, default 1)
%
% Out:
%   A - Transition matrix
%   Q - Discrete Process Covariance
%
% Description:
%   Discretize LTI ODE with Gaussian Noise. The original
%   ODE model is in form
%
%     dx/dt = F x + L w,  w ~ N(0,Qc)
%
%   Result of discretization is the model
%
%     x[k] = A x[k-1] + q, q ~ N(0,Q)
%
%   Which can be used for integrating the model
%   exactly over time steps, which are multiples
%   of dt.
% History:
%   11.01.2003  Covariance propagation by matrix fractions
%   20.11.2002  The first official version.
%
% Copyright (C) 2002, 2003 Simo Särkkä
%
% $Id: lti_disc.m,v 1.1 2005/08/02 11:10:47 ssarkka Exp $
%
% This software is distributed under the GNU General Public
% Licence (version 2 or later); please refer to the file
% Licence.txt, included with the software, for details.
function [A,Q] = lti_disc(F,L,Q,dt)
  %
  % Check number of arguments
  %
  if nargin < 1
    error('Too few arguments');
  end
  if nargin < 2
    L = [];
  end
  if nargin < 3
    Q = [];
  end
  if nargin < 4
    dt = [];
  end
  if isempty(L)
    L = eye(size(F,1));
  end
  if isempty(Q)
    Q = zeros(size(F,1),size(F,1));
  end
  if isempty(dt)
    dt = 1;
  end
  %
  % Closed form integration of transition matrix
  %
  A = expm(F*dt);
  %
  % Closed form integration of covariance
  % by matrix fraction decomposition
  %
  n   = size(F,1);
  Phi = [F L*Q*L'; zeros(n,n) -F'];
  AB  = expm(Phi*dt)*[zeros(n,n);eye(n)];
  Q   = AB(1:n,:)/AB((n+1):(2*n),:);