Description of bot_h
Home > src > demos > bot_demo > bot_h.m
bot_h
PURPOSE
Azimuth measurement function for EKF/UKF.
SYNOPSIS
function Y = bot_h(x,s)
DESCRIPTION
 Azimuth measurement function for EKF/UKF.
  h = atan((y-sy) / (x-sx))
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bot_demo_all Bearings Only Tracking (BOT) demonstration with EKF1,EKF2 and UKF
ekfs_bot_demo Bearings Only Tracking (BOT) demonstration with EKF
ukfs_bot_demo Bearings Only Tracking (BOT) demonstration with UKF.
SOURCE CODE
% Azimuth measurement function for EKF/UKF.
%
%  h = atan((y-sy) / (x-sx))
%
% Copyright (C) 2003 Simo Särkkä
%
% This software is distributed under the GNU General Public
% Licence (version 2 or later); please refer to the file
% Licence.txt, included with the software, for details.
function Y = bot_h(x,s)
  Y = zeros(size(s,2),size(x,2));
  for i=1:size(s,2)
    h = atan2(x(2,:)-s(2,i),x(1,:)-s(1,i));
    np = find(h>0.5*pi);
    nn = find(h<-0.5*pi);
    if length(nn)>length(np)
      h(np) = h(np)-2*pi;
    else
      h(nn) = h(nn)+2*pi;
    end
    Y(i,:) = h;
  end