Description of ukf_update3
Home > src > ukf_update3.m
ukf_update3
PURPOSE
UKF_UPDATE2 - Augmented form Unscented Kalman Filter update step
SYNOPSIS
function [M,P,K,MU,S,LH] = ukf_update3(M,P,Y,h,R,X,w,param,alpha,beta,kappa,mat)
DESCRIPTION
UKF_UPDATE2 - Augmented form Unscented Kalman Filter update step
 Syntax:
   [M,P,K,IM,IS,LH] = UKF_UPDATE3(M,P,Y,h,R,X,w,param,alpha,beta,kappa,mat,sigmas)
 In:
   M  - Mean state estimate after prediction step
   P  - State covariance after prediction step
   Y  - Measurement vector.
   h  - Measurement model function as a matrix H defining
        linear function h(x) = H*x, inline function,
        function handle or name of function in
        form h(x,param)
   R  - Measurement covariance.
   X - Sigma points of x
   w - Weights as cell array {mean-weights,cov-weights,c}
   param - Parameters of a               (optional, default empty)
   alpha - Transformation parameter      (optional)
   beta  - Transformation parameter      (optional)
   kappa - Transformation parameter      (optional)
   mat   - If 1 uses matrix form         (optional, default 0)
 Out:
   M  - Updated state mean
   P  - Updated state covariance
   K  - Computed Kalman gain
   MU - Predictive mean of Y
   S  - Predictive covariance Y
   LH - Predictive probability (likelihood) of measurement.
 Description:
   Perform augmented form Discrete Unscented Kalman Filter (UKF)
   measurement update step. Assumes additive measurement
   noise.
   Function h should be such that it can be given
   DxN matrix of N sigma Dx1 points and it returns
   the corresponding measurements for each sigma
   point. This function should also make sure that
   the returned sigma points are compatible such that
   there are no 2pi jumps in angles etc.
 Example:
   h = inline('atan2(x(2,:)-s(2),x(1,:)-s(1))','x','s');
   [M2,P2] = ukf_update2(M1,P1,Y,h,R,S);
 See also:
   UKF_PREDICT1, UKF_PREDICT2, UT_TRANSFORM, UT_WEIGHTS, UT_MWEIGHTS,
   UT_SIGMAS
 History:
   04.05.2007 JH Initial version. Modified from ukf_update1.m
              originally created by SS.
 References:
   [1] Wan, Merwe: The Unscented Kalman Filter
CROSS-REFERENCE INFORMATION
This function calls:
gauss_pdf GAUSS_PDF Multivariate Gaussian PDF
ut_transform UT_TRANSFORM Perform unscented transform
This function is called by:
dreentry_demo Discrete-time reentry demonstration using EKF and UKF.
ekf_sine_demo Demonstration for EKF using a random sine signal model.
ungm_demo Demonstration of univariate nonstationary growth model (UNGM) using EKF and UKF.
ungm_demo Demonstration of univariate nonstationary growth model (UNGM) using
SOURCE CODE
%UKF_UPDATE2 - Augmented form Unscented Kalman Filter update step
%
% Syntax:
%   [M,P,K,IM,IS,LH] = UKF_UPDATE3(M,P,Y,h,R,X,w,param,alpha,beta,kappa,mat,sigmas)
%
% In:
%   M  - Mean state estimate after prediction step
%   P  - State covariance after prediction step
%   Y  - Measurement vector.
%   h  - Measurement model function as a matrix H defining
%        linear function h(x) = H*x, inline function,
%        function handle or name of function in
%        form h(x,param)
%   R  - Measurement covariance.
%   X - Sigma points of x
%   w - Weights as cell array {mean-weights,cov-weights,c}
%   param - Parameters of a               (optional, default empty)
%   alpha - Transformation parameter      (optional)
%   beta  - Transformation parameter      (optional)
%   kappa - Transformation parameter      (optional)
%   mat   - If 1 uses matrix form         (optional, default 0)
%
% Out:
%   M  - Updated state mean
%   P  - Updated state covariance
%   K  - Computed Kalman gain
%   MU - Predictive mean of Y
%   S  - Predictive covariance Y
%   LH - Predictive probability (likelihood) of measurement.
%
% Description:
%   Perform augmented form Discrete Unscented Kalman Filter (UKF)
%   measurement update step. Assumes additive measurement
%   noise.
%
%   Function h should be such that it can be given
%   DxN matrix of N sigma Dx1 points and it returns
%   the corresponding measurements for each sigma
%   point. This function should also make sure that
%   the returned sigma points are compatible such that
%   there are no 2pi jumps in angles etc.
%
% Example:
%   h = inline('atan2(x(2,:)-s(2),x(1,:)-s(1))','x','s');
%   [M2,P2] = ukf_update2(M1,P1,Y,h,R,S);
%
% See also:
%   UKF_PREDICT1, UKF_PREDICT2, UT_TRANSFORM, UT_WEIGHTS, UT_MWEIGHTS,
%   UT_SIGMAS
%
% History:
%   04.05.2007 JH Initial version. Modified from ukf_update1.m
%              originally created by SS.
%
%
% References:
%   [1] Wan, Merwe: The Unscented Kalman Filter
% Copyright (C) 2007 Jouni Hartikainen, Simo Särkkä
%
% $Id: ukf_update1.m,v 1.1 2006/09/26 21:32:41 ssarkka Exp $
%
% This software is distributed under the GNU General Public
% Licence (version 2 or later); please refer to the file
% Licence.txt, included with the software, for details.
function [M,P,K,MU,S,LH] = ukf_update3(M,P,Y,h,R,X,w,param,alpha,beta,kappa,mat)
  %
  % Check that all arguments are there
  %
  if nargin < 5
    error('Too few arguments');
  end
  if nargin < 9
    param = [];
  end
  if nargin < 10
    alpha = [];
  end
  if nargin < 11
    beta = [];
  end
  if nargin < 12
    kappa = [];
  end
  if nargin < 13
    mat = [];
  end
  %
  % Apply defaults
  %
  if isempty(mat)
    mat = 0;
  end
  %
  % Do transform and make the update
  %
  [MU,S,C,X,Y_s] = ut_transform(M,P,h,param,alpha,beta,kappa,mat,X,w);
  K = C * inv(S);
  M = M + K * (Y - MU);
  P = P - K * S * K';
  if nargout > 5
    LH = gauss_pdf(Y,MU,S);
  end